### ISSUE TITLE
d2l-tvm-colab can't open

### ISSUE THREAD

**Issue by StevenJokes** [d2l-ai/d2l-tvm#44]
![image](https://user-images.githubusercontent.com/25657787/90340639-4a6c0f00-e02c-11ea-817d-3d08dcca499a.png)

**Comment by StevenJokes** [comment]
![image](https://user-images.githubusercontent.com/25657787/90340962-3aedc580-e02e-11ea-919d-15fcc1068dac.png)
We don't need these brackets. How to delete them?

**Comment by StevenJokes** [comment]
Maybe we need to use the newest `d2lbook` to build again?
I can't find any problem here. https://github.com/d2l-ai/d2l-tvm/edit/master/config.ini

**Comment by mli** [comment]
fixed

**Comment by StevenJokes** [comment]
Thanks. I got why the ini errors.
